### ISSUE TITLE
Server won't start

### ISSUE THREAD

**Issue by joeynimu** [n1ru4l/graphql-bleeding-edge-playground#288]
Hey @n1ru4l ,

I still can't get the server to start, the `yarn server:start` script errors as below;

```
jngethe@Joes-MacBook-Pro graphql-bleeding-edge-playground % yarn server:start
yarn run v1.22.5
$ cross-env NODE_ENV=development node --experimental-specifier-resolution=node --loader ts-node/esm ./server/main.ts
(node:47920) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
/Users/jngethe/Desktop/graphql-bleeding-edge-playground/node_modules/ts-node/dist-raw/node-esm-resolve-implementation.js:397
  throw new ERR_PACKAGE_PATH_NOT_EXPORTED(
        ^
CustomError: ERR_PACKAGE_PATH_NOT_EXPORTED /Users/jngethe/Desktop/graphql-bleeding-edge-playground/node_modules/graphql-helix/ . /Users/jngethe/Desktop/graphql-bleeding-edge-playground/server/main.ts
    at throwExportsNotFound (/Users/jngethe/Desktop/graphql-bleeding-edge-playground/node_modules/ts-node/dist-raw/node-esm-resolve-implementation.js:397:9)
    at packageExportsResolve (/Users/jngethe/Desktop/graphql-bleeding-edge-playground/node_modules/ts-node/dist-raw/node-esm-resolve-implementation.js:586:7)
    at packageResolve (/Users/jngethe/Desktop/graphql-bleeding-edge-playground/node_modules/ts-node/dist-raw/node-esm-resolve-implementation.js:763:14)
    at moduleResolve (/Users/jngethe/Desktop/graphql-bleeding-edge-playground/node_modules/ts-node/dist-raw/node-esm-resolve-implementation.js:815:18)
    at Object.defaultResolve (/Users/jngethe/Desktop/graphql-bleeding-edge-playground/node_modules/ts-node/dist-raw/node-esm-resolve-implementation.js:929:11)
    at /Users/jngethe/Desktop/graphql-bleeding-edge-playground/node_modules/ts-node/src/esm.ts:68:38
    at Generator.next (<anonymous>)
    at /Users/jngethe/Desktop/graphql-bleeding-edge-playground/node_modules/ts-node/dist/esm.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/jngethe/Desktop/graphql-bleeding-edge-playground/node_modules/ts-node/dist/esm.js:4:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
I am not sure if anyone else is getting this error or it's specific to me.

**Comment by joeynimu** [comment]
@n1ru4l Thank you. I have pulled and ran the script again, now getting another different error;

```
/Users/jngethe/Desktop/graphql-bleeding-edge-playground/node_modules/ts-node/dist-raw/node-esm-resolve-implementation.js:369
    throw new ERR_MODULE_NOT_FOUND(
          ^
CustomError: Cannot find module '/Users/jngethe/Desktop/graphql-bleeding-edge-playground/node_modules/graphql-helix/dist-esm/index.mjs' imported from /Users/jngethe/Desktop/graphql-bleeding-edge-playground/server/main.ts
    at finalizeResolution (/Users/jngethe/Desktop/graphql-bleeding-edge-playground/node_modules/ts-node/dist-raw/node-esm-resolve-implementation.js:369:11)
    at moduleResolve (/Users/jngethe/Desktop/graphql-bleeding-edge-playground/node_modules/ts-node/dist-raw/node-esm-resolve-implementation.js:818:10)
    at Object.defaultResolve (/Users/jngethe/Desktop/graphql-bleeding-edge-playground/node_modules/ts-node/dist-raw/node-esm-resolve-implementation.js:929:11)
    at /Users/jngethe/Desktop/graphql-bleeding-edge-playground/node_modules/ts-node/src/esm.ts:68:38
    at Generator.next (<anonymous>)
    at /Users/jngethe/Desktop/graphql-bleeding-edge-playground/node_modules/ts-node/dist/esm.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/jngethe/Desktop/graphql-bleeding-edge-playground/node_modules/ts-node/dist/esm.js:4:12)
    at resolve (/Users/jngethe/Desktop/graphql-bleeding-edge-playground/node_modules/ts-node/dist/esm.js:32:16)
    at Loader.resolve (internal/modules/esm/loader.js:86:40)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by n1ru4l** [comment]
fixed
